const UPDATE_INFO = 'UPDATE_INFO'
const ADD_ARTICLES_ERROR = 'ADD_ARTICLES_ERROR'
const SWITCH_VISIBLE = 'SWITCH_VISIBLE'
const CHANGE_ADD_FORM = 'CHANGE_ADD_FORM'
const UPDATE_POSTS = 'UPDATE_POSTS'
const DELETE_ADD_FORM = 'DELETE_ADD_FORM'
const DELETE_POST = 'DELETE_POST'
const PUT_POST = 'PUT_POST'
const EDIT_ADD_FORM = 'EDIT_ADD_FORM'
const CHANGE_EDIT_FORM = 'CHANGE_EDIT_FORM'
const EDIT_MODE = 'EDIT_MODE'

export {
  UPDATE_INFO,
  ADD_ARTICLES_ERROR,
  SWITCH_VISIBLE,
  CHANGE_ADD_FORM,
  UPDATE_POSTS,
  DELETE_ADD_FORM,
  DELETE_POST,
  EDIT_ADD_FORM,
  CHANGE_EDIT_FORM,
  EDIT_MODE,
  PUT_POST,
}
